imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    translator: { fallback: en }
    session:
        default_locale: %locale%
        auto_start:     true
        lifetime:       72000

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        hostname: %hostname%
        directory: %directory%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  utf8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# fos rest configuration
fos_rest:
    view:
        formats:
            json: true
            rss: false
            xml: false
        templating_formats:
            html: true
        force_redirects:
            html: true
        failed_validation: HTTP_BAD_REQUEST
        default_engine: twig
        
# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    encryption: %mailer_encryption%    

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

services:
    item_loader:
        class:        Zeega\IngestBundle\ItemLoader
    import_widget:
        class:      Zeega\IngestBundle\ImportWidget

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: secured_area
    user_class: Zeega\UserBundle\Entity\User
    from_email:
        address: noreply@zeega.org
        sender_name: Zeega
    registration:
        form:
            type: zeega_user_registration
    resetting:
        email:
            template: ZeegaUserBundle:Email:resetting.email.twig